###############################################
TARGET_ARCH = arm
TARGET_ARCH_VARIANT = armv7-a-neon
TARGET_CPU_VARIANT = cortex-a9
TARGET_BOARD_PLATFORM = imx6
TARGET_NO_BOOTLOADER = true
TARGET_NO_KERNEL = false
TARGET_NO_RECOVERY = false
TARGET_NO_RADIOIMAGE = true
TARGET_CPU_ABI = armeabi-v7a
TARGET_CPU_ABI2 = armeabi
BOARD_WLAN_DEVICE = true
BOARD_USES_GENERIC_AUDIO = false
#BOARD_KERNEL_CMDLINE 
BOARD_KERNEL_BASE = 0x10800000
BOARD_HAVE_BLUETOOTH = true
#############################################
BOARD_BOOTIMAGE_PARTITION_SIZE = 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE = 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE = 1073741824
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE = ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE = ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE = 629145600
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE = ext4
BOARD_CACHEIMAGE_PARTITION_SIZE = 62914560 
BOARD_FLASH_BLOCK_SIZE = 512
#############################################
